name: Check Secret Length

on:
  workflow_dispatch:  # lets you run manually from GitHub Actions tab

jobs:
  check-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Print length of SAKSH key
        run: |
          echo -n "${{ secrets.SAKSH }}" | wc -c
